name: Build executables

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :composeApp:createDistributable

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p artifacts
          cp composeApp/build/compose/binaries/main/app/Stub/*.exe artifacts/ 2>/dev/null || true
          cp composeApp/build/compose/binaries/main/app/*.deb artifacts/ 2>/dev/null || true
          cp composeApp/build/compose/binaries/main/app/*.dmg artifacts/ 2>/dev/null || true

      - name: Create zip
        shell: bash
        run: |
          cd artifacts && zip -r ../executables.zip *

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: executables.zip