name: Build executables

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Windows EXE
        run: ./gradlew :composeApp:packageDesktopForWindows

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          path: composeApp/build/compose/binaries/main/app/Stub/*.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Mac DMG
        run: ./gradlew :composeApp:packageDesktopForMac

      - name: Upload Mac DMG
        uses: actions/upload-artifact@v4
        with:
          path: composeApp/build/compose/binaries/main/app/*.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Linux DEB
        run: ./gradlew :composeApp:packageDesktopForLinux

      - name: Upload Linux DEB
        uses: actions/upload-artifact@v4
        with:
          path: composeApp/build/compose/binaries/main/app/*.deb